"""Actual ECharts dataset/typed-array and visually hidden reading-text evidence."""
from pathlib import Path
import argparse,json
from playwright.sync_api import sync_playwright
ap=argparse.ArgumentParser();ap.add_argument('--chrome',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();root=Path(__file__).resolve().parents[1];out=[]
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path=a.chrome);p=b.new_page();errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
 p.set_content('<div id=card style="width:340px;height:240px;padding:20px"><div id=chart class=kz-chart style="width:300px;height:200px"></div></div>');p.add_script_tag(path=str(root/'assets/vendor/echarts.min.js'));p.add_script_tag(path=str(root/'runtime/kz-layout-qc.js'));p.evaluate("window.realChart=echarts.init(document.querySelector('#chart'))")
 cases=[('dataset',"{animation:false,dataset:{source:[['阶段','数值'],['甲',1],['乙',2]]},xAxis:{type:'category'},yAxis:{type:'value'},series:[{type:'bar'}]}",2),('filtered empty dataset',"{animation:false,dataset:[{source:[['阶段','数值'],['甲',1],['乙',2]]},{transform:{type:'filter',config:{dimension:'数值',gt:10}}}],xAxis:{type:'category'},yAxis:{type:'value'},series:[{type:'bar',datasetIndex:1}]}",0),('typed array',"{animation:false,xAxis:{type:'value'},yAxis:{type:'value'},series:[{type:'scatter',dimensions:['x','y'],data:new Float32Array([1,2,3,4])}]}",2)]
 for name,option,count in cases:
  p.evaluate('realChart.setOption('+option+',true)');r=p.evaluate("({qc:KZLayoutQC.inspectCard(document.querySelector('#card')),count:realChart.getModel().getSeries()[0].getData().count(),version:echarts.version})");assert r['count']==count and (r['qc']['status']=='EMPTY')==(count==0),(name,r);out.append({'name':name,'observed':r})
 r=p.evaluate("()=>{window.importedLibrary=echarts;window.echarts=undefined;const card=document.querySelector('#card');return{unknown:KZLayoutQC.inspectCard(card),injected:KZLayoutQC.inspectCard(card,{chartLibrary:importedLibrary})};}");assert r['unknown']['status']=='NOT_TESTED' and r['injected']['status']!='EMPTY',r;out.append({'name':'module import requires actual instance, not fake empty','observed':r})
 p.set_content('<div id=card style="position:relative;width:300px;height:200px;padding:20px"><p id=visible style="margin:0">可见正文</p><span style="position:absolute;clip:rect(0,0,0,0);top:-30px">仅辅助阅读文本</span></div>');p.add_script_tag(path=str(root/'runtime/kz-layout-qc.js'));r=p.evaluate("({card:KZLayoutQC.inspectCard(document.querySelector('#card')),text:KZLayoutQC.inspectTextBounds(document.querySelector('#card'))})");assert 'TEXT_OUTSIDE' not in r['card']['flags'] and r['text']['status']=='PASS',r;out.append({'name':'fully clipped auxiliary text excluded','observed':r})
 p.evaluate("document.querySelector('#visible').remove()");r=p.evaluate("({card:KZLayoutQC.inspectCard(document.querySelector('#card')),text:KZLayoutQC.inspectTextBounds(document.querySelector('#card'))})");assert r['card']['status']=='EMPTY' and r['text']['status']=='EMPTY',r;out.append({'name':'auxiliary text alone is not visible content','observed':r});assert not errors,errors;b.close()
Path(a.output).write_text(json.dumps({'checks':out,'errors':errors},ensure_ascii=False,indent=2));print(str(len(out))+' actual ECharts and clipping checks passed')
