"""Actual browser: one business text writer while the same film retains geometry."""
from pathlib import Path
import argparse,json
from playwright.sync_api import sync_playwright
ap=argparse.ArgumentParser();ap.add_argument('--chrome',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();root=Path(__file__).resolve().parents[1]
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path=a.chrome);p=b.new_page();p.set_content('<div id=f><div class=kz-film-stage style="position:relative;width:800px;height:400px"><div class=kz-film-carrier style="position:absolute"><span class=kz-film-carrier-label>业务标题</span><p class=kz-film-caption>业务说明</p></div></div></div>');p.add_script_tag(path=str(root/'runtime/kz-motion.js'))
 result=p.evaluate("""()=>{const frame=t=>({t,x:.1,y:.1,w:.6,h:.6,r:.1,tint:[255,249,240,.7],label:'几何帧标题',caption:'几何帧说明'});let f=new KZMotion.Film(document.querySelector('#f'),{frames:[frame(0),frame(.3),frame(.7),frame(1)],managedText:false});f.pause('probe');const el=f.carrier,observer=new MutationObserver(()=>{});observer.observe(el,{subtree:true,childList:true});f.seek(.2);f.seek(.3);const before={label:f.label.textContent,caption:f.caption.textContent,mutations:observer.takeRecords().length,sameNode:f.snapshot().sameNode};f.managedText=true;f.seek(.4);const after={label:f.label.textContent,caption:f.caption.textContent,sameNode:f.snapshot().sameNode};f.dispose();return{before,after};}""");assert result['before']=={'label':'业务标题','caption':'业务说明','mutations':0,'sameNode':True},result;assert result['after']['label']=='几何帧标题' and result['after']['caption']=='几何帧说明' and result['after']['sameNode'],result
 p.set_content('<div id=zero data-kz-tilt=0 style="width:200px;height:100px"></div><div id=default data-kz-tilt style="width:200px;height:100px"></div><div id=chart class=kz-chart data-kz-tilt=10 style="width:200px;height:100px"></div><div id=tablecard data-kz-tilt=10 style="width:200px;height:100px"><table><tr><td>数据表格</td></tr></table></div>');p.add_script_tag(path=str(root/'runtime/kz-motion.js'))
 tilt=p.evaluate("""()=>{const m=KZMotion.mountTilt(document),out={};for(const id of ['zero','default','chart','tablecard']){const el=document.getElementById(id),r=el.getBoundingClientRect();el.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerType:'mouse',clientX:r.left+r.width*.1,clientY:r.top+r.height*.1}));out[id]={transform:el.style.transform,light:el.style.getPropertyValue('--kz-mx')};}m.dispose();return out;}""");assert 'rotateX(0deg)' in tilt['zero']['transform'] and 'rotateY(0deg)' in tilt['zero']['transform'],tilt;assert 'rotateX(8deg)' in tilt['default']['transform'],tilt;assert tilt['chart']['transform']=='' and tilt['tablecard']['transform']=='',tilt;result['tilt']=tilt;b.close()
Path(a.output).write_text(json.dumps(result,ensure_ascii=False,indent=2));print('Business-owned text remains stable; default frame text and persistent carrier verified.')
