"""Actual lifecycle and clipping probes for independently raised edge cases."""
from pathlib import Path
import argparse,json
from playwright.sync_api import sync_playwright
ap=argparse.ArgumentParser();ap.add_argument('--chrome',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();R=Path(__file__).resolve().parents[1];report={}
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path=a.chrome);p=b.new_page()
 p.set_content('<div id=f><div class=kz-film-stage style="position:relative;width:800px;height:400px"><div class=kz-film-carrier style="position:absolute"><span class=kz-film-carrier-label></span><p class=kz-film-caption></p></div></div></div><div id=fresh data-kz-tilt=0 style="width:200px;height:100px"></div><div id=existing class=kz-tilt data-kz-tilt=0 style="width:200px;height:100px"></div>');p.add_script_tag(path=str(R/'runtime/kz-motion.js'))
 report['ownership']=p.evaluate('''()=>{const root=document.querySelector('#f'),frame=t=>({t,x:.1,y:.1,w:.6,h:.6,r:.1,tint:[255,249,240,.7],label:'起始',caption:'说明'}),options={frames:[frame(0),frame(.3),frame(.7),frame(1)]};let first=new KZMotion.Film(root,options),rejected=false;first.pause('qc');try{new KZMotion.Film(root,options)}catch(e){rejected=/已由另一时钟/.test(e.message)}const before=first.snapshot();first.dispose();const stateCleared=!('kzReady' in root.dataset)&&!('kzProgress' in root.dataset);let second=new KZMotion.Film(root,options);second.pause('qc');const remounted=second.snapshot().sameNode&&second.carrier===first.carrier;second.dispose();const tilt=KZMotion.mountTilt(document);tilt.dispose();return{rejected,before,remounted,stateCleared,freshClass:document.querySelector('#fresh').classList.contains('kz-tilt'),existingClass:document.querySelector('#existing').classList.contains('kz-tilt')};}''')
 o=report['ownership'];assert o['stateCleared'] and o['rejected'] and o['before']['sameNode'] and not o['before']['running'] and o['remounted'] and not o['freshClass'] and o['existingClass'],o
 p.set_content('<div id=root style="width:300px;height:120px;font:20px/32px sans-serif"><div id=clip style="border:12px solid transparent;width:100px;height:70px;overflow:hidden;position:relative"><p style="position:relative;left:-10px;margin:0;white-space:nowrap">边框区域裁切文字</p></div></div>');p.add_script_tag(path=str(R/'runtime/kz-layout-qc.js'));q=p.evaluate('KZLayoutQC.inspectTextBounds(document.querySelector("#root"))');assert q['status']=='FAIL' and any(x['reason']=='ancestor-clip' for x in q['failures']),q;report['borderClip']=q;b.close()
Path(a.output).write_text(json.dumps(report,ensure_ascii=False,indent=2));print('Actual browser ownership, remount, class restoration and clipping checks passed')
