"""Real Chrome regressions for R7 independent findings, including live WAAPI ownership."""
from pathlib import Path
import argparse,json
from playwright.sync_api import sync_playwright
ap=argparse.ArgumentParser();ap.add_argument('--chrome',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();R=Path(__file__).resolve().parents[1];out={}
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path=a.chrome);p=b.new_page();errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
 p.set_content('<div id=outer><div id=inner><div id=t data-kz-reveal>中文正文</div></div></div>');p.add_script_tag(path=str(R/'runtime/kz-motion.js'))
 out['pageBlocksDirect']=p.evaluate('''()=>{const root=document.querySelector('#inner'),t=document.querySelector('#t'),life=KZMotion.mountPage(root);life.enter();let rejected=false;const before=t.getAnimations().length;try{KZMotion.reveal(document.querySelector('#outer'))}catch(e){rejected=true}const after=t.getAnimations().length;life.dispose();return{rejected,before,after};}''');assert out['pageBlocksDirect']=={'rejected':True,'before':1,'after':1},out
 out['directBlocksBoth']=p.evaluate('''async()=>{const root=document.querySelector('#inner'),seq=KZMotion.reveal(root);let direct=false,page=false;try{KZMotion.reveal(document.querySelector('#outer'))}catch(e){direct=true}try{KZMotion.mountPage(root)}catch(e){page=true}await seq.finished;const life=KZMotion.mountPage(root);life.dispose();return{direct,page,released:true};}''');assert all(out['directBlocksBoth'].values()),out
 out['exitHold']=p.evaluate('''async()=>{const root=document.querySelector('#inner'),seq=KZMotion.reveal(root,{exit:true});await seq.finished;let held=false;try{KZMotion.reveal(root)}catch(e){held=true}const opacity=getComputedStyle(document.querySelector('#t')).opacity;seq.cancel();seq.cancel();const next=KZMotion.reveal(root);await next.finished;return{held,opacity,released:getComputedStyle(document.querySelector('#t')).opacity};}''');assert out['exitHold']=={'held':True,'opacity':'0','released':'1'},out
 p.set_content('<div id=f><div class=kz-film-stage style="width:1200px;height:400px;position:relative"><div class=kz-film-carrier style="position:absolute"><span class=kz-film-carrier-label></span></div></div><p class=kz-film-caption></p></div>');p.add_script_tag(path=str(R/'runtime/kz-motion.js'))
 out['film']=p.evaluate('''()=>{const root=document.querySelector('#f'),fr=t=>({t,x:.4,y:.1,w:.08,h:.5,r:.1,tint:[255,249,240,.7],label:'开始',caption:'说明'}),frames=[fr(0),fr(.3),fr(.7),fr(1)];let bad=frames.map(x=>({...x}));delete bad[1].label;let missingRejected=false;try{new KZMotion.Film(root,{frames:bad})}catch(e){missingRejected=true}const noMutation=!root.querySelector('.kz-film-carrier').dataset.kzCarrierId;let invalidRejected=false;try{new KZMotion.Film(root,{frames,minCarrierWidth:NaN})}catch(e){invalidRejected=true}const f=new KZMotion.Film(root,{frames});f.pause('qc');let snapshot=f.snapshot(),actual=f.carrier.getBoundingClientRect().width;root.querySelector('.kz-film-stage').style.width='600px';f.render();let resized=f.snapshot().geometry;f.dispose();const before=f.snapshot();f.seek(.8);f.pause('hidden');f.resume('disposed');const after=f.snapshot();let business=new KZMotion.Film(root,{frames:bad,managedText:false,minCarrierWidth:0});business.pause('qc');let exact=business.snapshot().geometry;business.dispose();return{missingRejected,noMutation,invalidRejected,snapshot,actual,resized,disposedStable:before.progress===after.progress&&JSON.stringify(before.reasons)===JSON.stringify(after.reasons),exact};}''')
 q=out['film'];assert q['missingRejected'] and q['noMutation'] and q['invalidRejected'] and q['disposedStable'],q;assert q['actual']==160 and q['snapshot']['geometry']['adjusted'] and q['snapshot']['geometry']['requested']['w']==.08,q;assert abs(q['resized']['effective']['w']-160/600)<.00001,q;assert not q['exact']['adjusted'],q
 p.set_content('<article id=hidden class=kz-card style="height:100px;width:200px;visibility:hidden">隐藏正文</article><article id=shown class=kz-card style="height:100px;width:200px">可见正文</article>');p.add_script_tag(path=str(R/'runtime/kz-layout-qc.js'));out['visibleCards']=p.evaluate('KZLayoutQC.inspect().map(x=>x.id)');assert out['visibleCards']==['shown'],out
 out['errors']=errors;assert not errors,errors;b.close()
Path(a.output).write_text(json.dumps(out,ensure_ascii=False,indent=2));print('R7 actual WAAPI/geometry/text/disposal/visibility regression passed')
