#!/usr/bin/env python3
"""Generate runtime tokens. The JSON is the single numeric/color authority."""
from pathlib import Path
import json
R = Path(__file__).resolve().parents[1]
def build():
    t = json.loads((R/'tokens/tokens.json').read_text())
    css = [':root {']
    for key, value in t['colors'].items(): css.append(f'  --kz-{key.replace("_","-")}: {value};')
    for key, value in t['type_px'].items(): css.append(f'  --kz-type-{key.replace("_","-")}: {value}px;')
    for key, value in t['departments'].items():
        css += [f'  --kz-{key}: {value["color"]};', f'  --kz-{key}-tint: {value["tint"]};']
    for label, stop in zip(['top','mid','bottom'], t['glass']['face_gradient']):
        color=stop['color'].lstrip('#');rgb=','.join(str(int(color[i:i+2],16)) for i in (0,2,4))
        css += [f'  --kz-face-{label}-rgb: {rgb};',f'  --kz-face-{label}-alpha: {stop["alpha"]};',f'  --kz-face-{label}-offset: {stop["offset"]*100:g}%;']
    color=t['glass']['border_color'].lstrip('#');rgb=','.join(str(int(color[i:i+2],16)) for i in (0,2,4))
    css += [f'  --kz-face-border-rgb: {rgb};',f'  --kz-face-border-alpha: {t["glass"]["border_alpha"]};']
    css += [f'  --kz-font: {t["fonts"]["fallback_css"]};',
            f'  --kz-radius: {t["glass"]["radius"]}px;',
            f'  --kz-radius-compact: {t["glass"]["radius_compact"]}px;',
            f'  --kz-radius-dialog: {t["glass"]["radius_dialog"]}px;',
            f'  --kz-blur: {t["glass"]["blur_px"]}px;',
            f'  --kz-gap: {t["rhythm"]["gap"]}px;',
            f'  --kz-pad: {t["rhythm"]["card_padding"]}px;',
            f'  --kz-card-alpha: {t["glass"]["face_alpha"]};',
            f'  --kz-line-body: {t["rhythm"]["line_height_body"]};',
            f'  --kz-float-period: {t["motion"]["float_period_ms"]}ms;',
            f'  --kz-float-amplitude: {t["motion"]["float_px"]}px;',
            f'  --kz-reference-height: {t["wide"]["htmlppt_reference_height"]};', '}']
    (R/'runtime/kz-tokens.css').write_text('/* Generated by tools/build_tokens.py; do not edit. */\n'+'\n'.join(css)+'\n')
    (R/'runtime/kz-tokens.js').write_text('/* Generated. Numeric authority: tokens/tokens.json */\nwindow.KZ_TOKENS = '+json.dumps(t,ensure_ascii=False,separators=(',',':'))+';\n')
if __name__ == '__main__': build()
